# Generated by Django 4.2.3 on 2023-08-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_category_alter_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="banner",
            field=models.ImageField(null=True, upload_to="media/bannerimage"),
        ),
    ]
