# Generated by Django 4.2.3 on 2023-08-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="image1",
            field=models.ImageField(blank=True, upload_to="image/productimage"),
        ),
        migrations.AddField(
            model_name="product",
            name="image10",
            field=models.ImageField(blank=True, upload_to="image/productimage"),
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(blank=True, upload_to="image/productimage"),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(blank=True, upload_to="image/productimage"),
        ),
        migrations.AddField(
            model_name="product",
            name="image4",
            field=models.ImageField(blank=True, upload_to="image/productimage"),
        ),
        migrations.AddField(
            model_name="product",
            name="image5",
            field=models.ImageField(blank=True, upload_to="image/productimage"),
        ),
        migrations.AddField(
            model_name="product",
            name="image6",
            field=models.ImageField(blank=True, upload_to="image/productimage"),
        ),
        migrations.AddField(
            model_name="product",
            name="image7",
            field=models.ImageField(blank=True, upload_to="image/productimage"),
        ),
        migrations.AddField(
            model_name="product",
            name="image8",
            field=models.ImageField(blank=True, upload_to="image/productimage"),
        ),
        migrations.AddField(
            model_name="product",
            name="image9",
            field=models.ImageField(blank=True, upload_to="image/productimage"),
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
