# Generated by Django 4.2.3 on 2023-08-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_remove_product_image_product_image1_product_image10_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image1",
            field=models.ImageField(null=True, upload_to="image/productimage"),
        ),
    ]
