# Generated by Django 4.2.3 on 2023-08-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_product_image1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image10",
            field=models.ImageField(null=True, upload_to="image/productimage"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image2",
            field=models.ImageField(null=True, upload_to="image/productimage"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image3",
            field=models.ImageField(null=True, upload_to="image/productimage"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image4",
            field=models.ImageField(null=True, upload_to="image/productimage"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image5",
            field=models.ImageField(null=True, upload_to="image/productimage"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image6",
            field=models.ImageField(null=True, upload_to="image/productimage"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image7",
            field=models.ImageField(null=True, upload_to="image/productimage"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image8",
            field=models.ImageField(null=True, upload_to="image/productimage"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image9",
            field=models.ImageField(null=True, upload_to="image/productimage"),
        ),
    ]
