# Generated by Django 4.2.3 on 2023-08-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_product_image10_alter_product_image2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image1",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image10",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image3",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image4",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image5",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image6",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image7",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image8",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image9",
        ),
    ]
