# Generated by Django 4.2.3 on 2023-08-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_rename_image1_product_image_remove_product_image10_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imagemodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/productimage")),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ManyToManyField(
                blank=True, related_name="galleries", to="store.imagemodel"
            ),
        ),
    ]
