# Generated by Django 4.2.3 on 2023-08-07 15:52

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_remove_product_image_delete_imagemodel_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="video",
            field=models.FileField(
                null=True,
                upload_to="media/video/%y",
                validators=[store.validators.filesize],
            ),
        ),
    ]
