# Generated by Django 4.2.3 on 2023-08-07 16:47

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_remove_product_image_product_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video_count",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="banner",
            field=models.ImageField(null=True, upload_to="bannerimage"),
        ),
        migrations.AlterField(
            model_name="product",
            name="video",
            field=models.FileField(
                null=True, upload_to="video/%y", validators=[store.validators.filesize]
            ),
        ),
    ]
