# Generated by Django 4.2.3 on 2023-08-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_alter_profile_profile_picture_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[
                    ("reveiwing", "reveiwing"),
                    ("declined", "declined"),
                    ("accepted", "accepted"),
                ],
                default="submited",
                max_length=100,
            ),
        ),
    ]
