# Generated by Django 4.2.3 on 2023-08-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_alter_vendor_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="image",
            field=models.ImageField(blank=True, upload_to="media/vendorinfo/"),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="identification",
            field=models.ImageField(blank=True, upload_to="media/vendorinfo/"),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[
                    ("reveiwing", "reveiwing"),
                    ("declined", "declined"),
                    ("accepted", "accepted"),
                ],
                default="reveiwing",
                max_length=100,
            ),
        ),
    ]
