# Generated by Django 4.2.3 on 2023-08-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0006_alter_vendor_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_submmited", "not_submmited"),
                    ("submitted", "submitted"),
                    ("declined", "declined"),
                    ("accepted", "accepted"),
                ],
                default="not_submmited",
                max_length=100,
            ),
        ),
    ]
