# Generated by Django 4.2.3 on 2023-08-02 23:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userprofile", "0013_remove_vendor_followers_alter_follow_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="followers",
            field=models.ManyToManyField(
                related_name="following_vendors", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
